//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Weight.rc
//
#define IDC_FETCHRECORD                 3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MAIN_DIALOG                 102
#define IDD_FREEWEIGHT_DIALOG           129
#define IDD_FORMULAMANAGEMENT_DIALOG    130
#define IDD_USERMANAGEMENT_DIALOG       131
#define IDD_MATERIALMANAGEMENT_DIALOG   132
#define IDD_SETTINGS_DIALOG             133
#define IDD_QUERY_DIALOG                135
#define IDD_MATERIALADD_DIALOG          136
#define IDD_USERADD_DIALOG              137
#define IDD_FORMULAADD_DIALOG           139
#define IDD_LOGIN_DIALOG                141
#define IDD_MATERIALCOUNTINPUT_DIALOG   142
#define IDD_FORMULASELECT_DIALOG        144
#define IDD_FORMULAWEIGH_DIALOG         145
#define IDD_FORMULANORMALWEIGH_DIALOG   146
#define IDD_FORMULASEPWEIGH_DIALOG      147
#define IDD_WEIGHPERPACK_DIALOG         148
#define IDD_PASSCHANGE_DIALOG           149
#define IDD_DETAILSRECORD_DIALOG        150
#define IDD_FETCHAMOUNTINTPUT_DIALOG    152
#define IDD_FORMULAADVANCEQUERY_DIALOG  157
#define IDB_SPLASH                      161
#define IDR_MAINFRAME                   166
#define IDB_MAINPAGE                    168
#define IDB_MATERIALMANAGEMENT          169
#define IDB_OTHERSETTINGS               172
#define IDB_USERMANAGEMENT              173
#define IDB_PASSWORDCHANGE              174
#define IDB_QUERY                       176
#define IDB_FREEWEIGHT                  180
#define IDB_STATISTIC                   181
#define IDB_FORMULAINPUT                182
#define IDB_FORMULASEPWEIGHT            184
#define IDB_FORMULAMANAGEMENT           185
#define IDB_FORMULAFETCH                186
#define IDB_FETCHRECORD                 187
#define IDB_FORMULAINDICATOR            189
#define IDB_WEIGHTBUTTON                190
#define IDB_DIVIDE                      191
#define IDB_FETCHAMOUNTINPUT            192
#define IDB_STATISTICSADVANCEQUERY      193
#define IDB_FETCHADVANCEQUERY           194
#define IDB_FORMULAADD                  195
#define IDB_MATERIALCOUNTINPUT          196
#define IDB_MATERIALINPUTCOUNT          197
#define IDD_BATCHNUMBERCHANGE           198
#define IDD_MAINSETTINGSDIALOG          199
#define IDD_BASIC_SETTINGS              199
#define IDD_WEIGHMANAGEMENT             200
#define IDB_MAINSETTINGS                201
#define IDB_WEIGHTSETTINGS              202
#define IDB_DLGBG                       206
#define IDB_BITMAP1                     209
#define IDB_LOGINBG                     209
#define IDD_BARCODE_MANAGEMENT          212
#define IDD_BARCODE_UPDATE              214
#define IDD_TRACE_DIALOG                215
#define IDD_QUERYCOND_DIALOG            216
#define IDD_DIALOG1                     218
#define IDD_QUERY_RESULT                218
#define IDD_PRODUCT_TRACE               219
#define IDC_WEIGHFREE_BUTTON            1003
#define IDC_STATISTIC_BUTTON            1005
#define IDC_FORMULAMANAGE_BUTTON        1008
#define IDC_USERMANAGEMENT              1009
#define IDC_OTHERSETTINGSBUTTON         1010
#define IDC_POWEROFF_BUTTON             1011
#define IDC_MATERIALMANAGEMENT_BUTTON   1012
#define IDC_CHANGEPASSWORD_BUTTON       1013
#define IDC_FORMULAWEIGH_BUTTON         1014
#define IDC_USERADD                     1017
#define IDC_USERDEL                     1018
#define IDC_MATERIALADD                 1019
#define IDC_MATERIALDEL                 1020
#define IDC_SERIAL_PORT1                1021
#define IDC_BATCHNUMBERCHANGE           1021
#define IDC_SERIAL_PORT2                1022
#define IDC_BACKUPDATABASE              1023
#define IDC_RESTOREDATABASE             1024
#define IDC_FORMULA_ADD                 1028
#define IDC_FORMULA_DEL                 1029
#define IDC_FORMULA_LISTCTRL            1031
#define IDC_USERLIST                    1032
#define IDC_MATERIALLIST                1033
#define IDC_MATERIALID_STATIC           1034
#define IDC_MATERIALNAME_STATIC         1035
#define IDC_MATERIALCOUNT_STATIC        1036
#define IDC_MATERIALNAME_STATIC2        1036
#define IDC_MATERIALBATCHNUMBER_STATIC  1037
#define IDC_MATERIALNAME_STATIC3        1037
#define IDC_MATERIALID_EDIT             1038
#define IDC_MATERIALNAME_EDIT           1039
#define IDC_MATERIALCOUNT_EDIT          1040
#define IDC_MATERIALNAME_EDIT2          1040
#define IDC_MATERIALBATCHNUMBER_EDIT    1041
#define IDC_MANUFACTURE                 1041
#define IDC_TIPS_STATIC                 1042
#define IDC_USERID_EDIT                 1044
#define IDC_TIPS_STATIC2                1044
#define IDC_USERNAME_EDIT               1045
#define IDC_USERID_STATIC               1046
#define IDC_USERNAME_STATIC             1047
#define IDC_USERRIGHT_STATIC            1048
#define IDC_USERRIGHT_DROPDOWN          1049
#define IDC_TIP_STATIC                  1050
#define IDC_COM1RATE_STATIC             1067
#define IDC_COM2RATE_STATIC             1068
#define IDC_COM1RATE_COMBO              1069
#define IDC_COM2RATE_COMBO              1070
#define IDC_DATABASESETTING_STATIC      1071
#define IDC_PASSWORD_STATIC             1072
#define IDC_PASSWORD_EDIT               1074
#define IDC_FORMULAID_STATIC            1078
#define IDC_FORMULAID_EDIT              1079
#define IDC_FORMULANAME_STATIC          1080
#define IDC_FORMULANAME_EDIT            1081
#define IDC_QUERYTABLE_STATIC           1085
#define IDC_INDEX_STATIC                1086
#define IDC_KEYWORD_STATIC              1087
#define IDC_KEYWORD_EDIT                1088
#define IDC_QUERYTABLE_COMBO            1089
#define IDC_QUERYINDEX_COMBO            1090
#define IDC_RESULT_LIST                 1091
#define ID_QUERY                        1092
#define IDC_CLEARRESULT_BUTTON          1094
#define IDC_INDEXNAME_STATIC            1096
#define IDC_FORMULASELECT_STATIC        1100
#define IDC_FORMULASELECT_COMBO         1101
#define IDC_LIST1                       1104
#define IDC_COM2DISPLAY_LIST            1104
#define IDC_WEIGH_EDIT                  1105
#define IDC_WEIGH_STATIC                1106
#define IDC_FORMULAWEIGH_STATIC         1109
#define IDC_WEIGH_BUTTON                1110
#define IDC_WEIGHDISPLAY_STATIC         1111
#define IDC_WEIGHDISPLAY_LIST           1112
#define IDC_MATERIALWEIGH_STATIC        1113
#define IDC_COM1WEIGHDISPLAY_LIST       1113
#define IDC_DIVIDE_BUTTON               1114
#define IDC_WEIGHEVERYPACK_STATIC       1115
#define IDC_MATERIALNEEDED_STATIC       1116
#define IDC_COM1DISPLAY_LIST            1121
#define IDC_COM1WEIGHDISPLAY_STATIC     1122
#define IDC_COM2WEIGHDISPLAY_STATIC     1123
#define IDC_COM2WEIGHDISPLAY_LIST       1124
#define IDC_WEIGHPERPACK_STATIC         1127
#define IDC_WEIGHPERPACK_EDIT           1128
#define IDC_ORIGINALPASS_STATIC         1129
#define IDC_NEWPASS_STATIC              1130
#define IDC_NEWPASSCONFIRM_STATIC       1131
#define IDC_ORIGINALPASS_EDIT           1132
#define IDC_NEWPASS_EDIT                1133
#define IDC_NEWPASSCONFIRM_EDIT         1134
#define IDC_FORMULAID_COMBO             1135
#define IDC_FORMULAMODIFY_BUTTON        1136
#define IDC_FORMULANAME                 1138
#define IDC_FORMULAWEIGH                1139
#define IDC_MATERIALNAME                1140
#define IDC_WEIGHPERPACK                1142
#define IDC_MATERIALWEIGHNEEDDISPLAY_STATIC 1143
#define IDC_PACKWEIGHT                  1143
#define IDC_PACKSNEED_STATIC            1144
#define IDC_PACKSNEED                   1145
#define IDC_ISMULTIPACKNEEDED           1146
#define IDC_MATERIALTOTAL               1147
#define IDC_MULTITIMES_NEEDED           1148
#define IDC_ALREADYWEIGHED              1149
#define IDC_PERCENTAGESECOND_STATIC     1150
#define IDC_WEIGHNEEDED                 1150
#define IDC_DATE_STATIC                 1152
#define IDC_TIME_STATIC                 1153
#define IDC_WEIGH1_STATIC               1156
#define IDC_WEIGH2_STATIC               1157
#define IDC_FETCHAMOUNT_EDIT            1158
#define IDC_FORMULAFETCH_BUTTON         1161
#define IDC_FORMULA_COMBO               1184
#define IDC_USER_COMBO                  1185
#define IDC_AMOUNT_COMBO                1186
#define IDC_DATE_COMBO                  1188
#define IDC_SUM_CHECK                   1189
#define IDC_FORMULA_EDIT                1190
#define IDC_USER_EDIT                   1191
#define IDC_AMOUNTFIRST_EDIT            1192
#define IDC_DATETIMEPICKER_FIRST        1193
#define IDC_DATETIMEPICKER_SECOND       1194
#define IDC_AMOUNTSECOND_EDIT           1195
#define IDC_BUTTON1                     1200
#define IDC_FETCHSTUFF_BUTTON           1201
#define IDC_BUTTON10                    1201
#define IDC_COM1DATA_STATIC             1202
#define IDC_BUTTON11                    1202
#define IDC_BUTTON2                     1203
#define IDC_COM2DATA_STATIC             1203
#define IDC_BUTTON3                     1204
#define IDC_STATUS_STATIC               1204
#define IDC_BUTTON7                     1205
#define IDC_BUTTON8                     1206
#define IDC_BUTTON9                     1207
#define IDC_BUTTON4                     1208
#define IDC_BUTTON5                     1209
#define IDC_BUTTON6                     1210
#define IDC_BUTTON0                     1211
#define IDC_BUTTON_COMMA                1212
#define IDC_BUTTON_BACK                 1213
#define IDC_STATUS_STATIC2              1214
#define IDC_STATUS_STATIC3              1214
#define IDC_STATUS_STATIC5              1215
#define IDC_STATIC6                     1216
#define IDC_STATIC10                    1217
#define IDC_STATUSSTATIC1111            1218
#define IDC_PRINT                       1219
#define IDC_PRINT_CHECK                 1220
#define IDC_MISSION_STATIC              1221
#define IDC_WEIGHT_STATIC               1222
#define IDC_BACK                        1232
#define IDC_GOBACK                      1233
#define IDC_BUTTONGOBACK                1234
#define IDC_GROSSWEIGHT                 1235
#define IDC_GOBACKBUTTON                1236
#define IDC_BATCHNUMBER                 1238
#define IDC_PRINTERCHECK                1239
#define IDC_PRIBUTTON                   1240
#define IDC_SECBUTTON                   1241
#define IDC_CANCEL                      1243
#define IDC_RESTNEEDED                  1244
#define IDC_BIG                         1246
#define IDC_FWBIG                       1246
#define IDC_SMALL                       1247
#define IDC_FWSMALL                     1247
#define IDC_FREEWEIGHT_LABEL            1248
#define IDC_FWLABEL                     1248
#define IDC_BARCODE_UPDATE              1250
#define IDC_LIST2                       1251
#define IDC_EDIT1                       1252
#define IDC_EDIT2                       1253
#define IDC_QUERY_LABEL                 1254
#define IDC_QUERY_ITEM                  1256
#define IDC_TIME_SECTION                1257
#define IDC_DATE_START                  1259
#define IDC_DATE_END                    1260
#define IDC_TIMESECTION_COMBO           1261
#define IDC_COMBO1                      1263
#define IDC_PRODUCT_LIST                1264
#define IDC_MATERIAL_LIST               1265
#define IDC_STATIC_SKIP                 1265
#define IDC_STATIC_RATIO                1266
#define IDC_STATIC_REAL                 1267
#define IDC_STATIC_CAUTION              1268
#define IDC_STATIC_SUM                  1269
#define IDC_CHECK1                      1270
#define IDC_MATERIAL_PRINT              1270

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        220
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1271
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
